config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  
  get 'pages/about', to: 'pages#about'
  get 'pages/contact', to: 'pages#contact'
  resources :pages
  resources :companies do
    resources :reviews, except: [:show, :index]
    collection do
      get 'search'
    end
end
  
  
  root to: 'companies#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/committee.rb
class Committee < ApplicationRecord
    has_many :directors
    belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :committees
    has_many :directors
    belongs_to :sector
end

app/models/director.rb
class Director < ApplicationRecord
    belongs_to :committee
    belongs_to :company
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :company
end

app/models/sector.rb
class Sector < ApplicationRecord
    has_many :companies
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
                                                          :email, 
                                                          :password, 
                                                          :password_confirmation, 
                                                          :username,
                                                          :first_name,
                                                          :last_name
                                                          ) 
                                                          }
  devise_parameter_sanitizer.for(:account_update) { |u| u.permit(
                                                          :email, 
                                                          :password, 
                                                          :password_confirmation, 
                                                          :current_password, 
                                                          :username,
                                                          :first_name,
                                                          :last_name
                                                          ) 
                                                          }  
  end
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  def index
  end
  
  def new
    @company = Company.new
  end
  
  def create
    @company = Company.new(company_params)
    @company.save
    redirect_to @company
  end
  
  def show
    @company = Company.find(params [:id])
  end
  
  
  private
  
  def company_params
    params.require(:company).permit(:name, :ticker, :description, :size, :url, :board_members, :avg_compensation)
  end
  
  
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
  end
  
  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/companies/index.html.erb
  <div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1>
          DeFacto 
        </h1>
      </div>
      <div class="col-lg-8 col-sm-8">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Add A Company", new_company_path %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>


<!--breadcrumbs end-->

<div class='container'>
  <div class="row">
    <div class="col-md-9">
<!--<%= render "companies/slider" %>  -->
</div>
    <div class="container">
<h3>Search DeFacto<br /><small> Company Search Tool</small></h3><hr>
    <%= form_tag search_companies_path, method: :get do |f| %>
    <div style="padding-bottom: 50px;" class="col-md-4">
    <%= text_field_tag :search, nil, placeholder: "Company Name?" %>
    </div>
    <div style="padding-bottom: 50px;" class="col-md-4">
    <%= text_field_tag :location, nil, placeholder: "Ticker?" %>
    </div>
    <%= select_tag :sector, 
        options_for_select(Sector.all.map{ |sector| [sector.name, sector.id]}) %>
    <%= submit_tag 'Search', class: "btn btn-info" %>
    <% end %>

  </div>
</div>


</div> <!--container end-->

app/views/companies/new.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1>
          DeFacto 
        </h1>
      </div>
      <div class="col-lg-8 col-sm-8">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Add A Company", new_company_path %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>
<div class="container">
    <%= simple_form_for @company do |form| %>
    <%= form.input :name %>
    <%= form.input :ticker %>
    <%= form.input :description %>
    <%= form.input :size %>
    <%= form.input :url %>
    <%= form.input :board_members %>
    <%= form.input :avg_compensation %>
    <%= form.submit "Create Company", class: "btn btn-warning" %>
    <% end %>
</div>

app/views/companies/show.html.erb
Show

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="container">
  <div class="row">
    <div class="col-lg-3 col-sm-3 address wow fadeInUp" data-wow-duration="2s" data-wow-delay=".1s">
      <h1>
        contact info
      </h1>
      <address>
        <p><i class="fa fa-home pr-10"></i>Address: 555 California Street</p>
        <p><i class="fa fa-globe pr-10"></i>San Francisco, CA </p>
        <p><i class="fa fa-mobile pr-10"></i>Mobile : (123) 456-7890 </p>
        <p><i class="fa fa-phone pr-10"></i>Phone : (123) 456-7890 </p>
        <p><i class="fa fa-envelope pr-10"></i>Email :   <a href="javascript:;">bobby@example.com</a></p>
      </address>
    </div>
    <div class="col-lg-3 col-sm-3 wow fadeInUp" data-wow-duration="2s" data-wow-delay=".3s">
      <h1>latest tweet</h1>
        <div class="tweet-box">
          <i class="fa fa-twitter"></i>
          <em>
            Please follow
            <a href="javascript:;">@example</a>
            for all future updates of us!
            <a href="javascript:;">twitter.com/acme</a>
          </em>
        </div>
        <div class="tweet-box">
          <i class="fa fa-twitter"></i>
          <em>
            Please follow
            <a href="javascript:;">@example</a>
            for all future updates of us!
            <a href="javascript:;">twitter.com/acme</a>
          </em>
        </div>
        <div class="tweet-box">
          <i class="fa fa-twitter"></i>
          <em>
            Please follow
            <a href="javascript:;">@example</a>
            for all future updates of us!
            <a href="javascript:;">twitter.com/acme</a>
          </em>
        </div>
    </div>
    <div class="col-lg-3 col-sm-3">
      <div class="page-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".5s">
        <h1>
          Our Company
        </h1>
        <ul class="page-footer-list">
          <li>
            <i class="fa fa-angle-right"></i>
            <a href="about.html">About Us</a>
          </li>
          <li>
            <i class="fa fa-angle-right"></i>
            <a href="faq.html">Support</a>
          </li>
          <li>
            <i class="fa fa-angle-right"></i>
            <a href="service.html">Service</a>
          </li>
          <li>
            <i class="fa fa-angle-right"></i>
            <a href="privacy-policy.html">Privacy Policy</a>
          </li>
          <li>
            <i class="fa fa-angle-right"></i>
            <a href="career.html">We are Hiring</a>
          </li>
          <li>
            <i class="fa fa-angle-right"></i>
            <a href="terms.html">Term & condition</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-lg-3 col-sm-3">
      <div class="text-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".7s">
        <h1>
          Text Widget
        </h1>
        <p>
          This is a text widget.Lorem ipsum dolor sit amet.
          This is a text widget.Lorem ipsum dolor sit amet.
        </p>
      </div>
    </div>
  </div>
</div>
</footer>
<!-- footer end -->
<!--small footer start -->
<footer class="footer-small">
  <div class="container">
      <div class="row">
          <div class="col-lg-6 col-sm-6 pull-right">
              <ul class="social-link-footer list-unstyled">
                  <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".1s"><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".2s"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                  <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".3s"><a href="#"><i class="fa fa-dribbble"></i></a></li>
                  <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".4s"><a href="#"><i class="fa fa-linkedin"></i></a></li>
                  <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".5s"><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".6s"><a href="#"><i class="fa fa-skype"></i></a></li>
                  <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".7s"><a href="#"><i class="fa fa-github"></i></a></li>
                  <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".8s"><a href="#"><i class="fa fa-youtube"></i></a></li>
              </ul>
          </div>
          <div class="col-md-4">
            <div class="copyright">
              	<p>  &copy; 2017 - <%= Time.now.strftime('%Y') %> <a href="https://defacto-proxy.herokuapp.com/">DeFacto</a> </p>
            </div>
          </div>
      </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="head-section">
  <div class="navbar navbar-default navbar-static-top container">
      <div class="navbar-header">
          <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
          De<span>Facto</span>
          <% end %>
      </div>
      <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            
              <li>
              <%= link_to pages_path, data: { close_others: false, delay: 0,
                hover: "dropdown"} do %>
                <i class="fa fa-home"></i> Home
              <% end %>
            <li>

              
                
            <li>
              <%= link_to root_path, data: { close_others: false, delay: 0,
                hover: "dropdown"} do %>
                <i class="fa fa-building"></i> Companies 
              <% end %>
            <li>
              
            <li>
              <%= link_to pages_about_path, data: { close_others: false, delay: 0,
                hover: "dropdown"} do %>
                <i class="fa fa-info-circle"></i> About Us
              <% end %>
            <li> 
               
            <li>
              <%= link_to pages_contact_path, data: { close_others: false, delay: 0,
                hover: "dropdown"} do %>
                <i class="fa fa-envelope"></i> Contact Us
              <% end %>
  
            

            <% if current_user %>
            <li>
              <%= link_to destroy_user_session_path, data: { close_others: false, delay: 0,
                hover: "dropdown"}, method: :delete do %>
                <i class="fa fa-stop-circle-o"></i> Sign Out
              <% end %>
            <li>
              <%= link_to edit_user_registration_path, data: { close_others: false, delay: 0,
                hover: "dropdown"} do %>
                <i class="fa fa-edit"></i> Edit My Profile
              <% end %>
            <li>  
            <% else %> 
            <li>
              <%= link_to new_user_session_path, data: { close_others: false, delay: 0,
                hover: "dropdown"} do %>
                <i class="fa fa-sign-in"></i> Sign In
              <% end %>
            <li>
            <li>
              <%= link_to new_user_registration_path, data: { close_others: false, delay: 0,
                hover: "dropdown"} do %>
                <i class="fa fa-registered"></i> Register
              <% end %>
            <li>   </ul>
            <% end %>
           
      </div>
  </div>
</header>

app/views/layouts/_script.html.erb
    <script src="js/jquery-1.8.3.min.js">
    </script>
    <script src="js/bootstrap.min.js">
    </script>
    <script type="text/javascript" src="js/hover-dropdown.js">
    </script>
    <script defer src="js/jquery.flexslider.js">
    </script>
    <script type="text/javascript" src="assets/bxslider/jquery.bxslider.js">
    </script>

    <script type="text/javascript" src="js/jquery.parallax-1.1.3.js">
    </script>
    <script src="js/wow.min.js">
    </script>
    <script src="assets/owlcarousel/owl.carousel.js">
    </script>

    <script src="js/jquery.easing.min.js">
    </script>
    <script src="js/link-hover.js">
    </script>
    <script src="js/superfish.js">
    </script>
    <script type="text/javascript" src="js/parallax-slider/jquery.cslider.js">
    </script>
    <script type="text/javascript">
      $(function() {
        $('#da-slider').cslider({
          autoplay    : true,
          bgincrement : 100
        });
      });
    </script>



    <!--common script for all pages-->
    <script src="js/common-scripts.js">
    </script>

    <script type="text/javascript">
      jQuery(document).ready(function() {
        $('.bxslider1').bxSlider({
          minSlides: 5,
          maxSlides: 6,
          slideWidth: 360,
          slideMargin: 2,
          moveSlides: 1,
          responsive: true,
          nextSelector: '#slider-next',
          prevSelector: '#slider-prev',
          nextText: 'Onward →',
          prevText: '← Go back'
        });
      });
    </script>


    <script>
      $('a.info').tooltip();
      $(window).load(function() {
        $('.flexslider').flexslider({
          animation: "slide",
          start: function(slider) {
            $('body').removeClass('loading');
          }
        });
      });
      $(document).ready(function() {
        $("#owl-demo").owlCarousel({
          items : 4
        });
      });
      jQuery(document).ready(function(){
        jQuery('ul.superfish').superfish();
      });
      new WOW().init();
    </script>
    
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Defacto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= bootstrap_flash %>
    
    <%= yield %>
    
    <%= render "layouts/footer" %>
    <%= render "layouts/script" %>
  </body>
</html>

app/views/pages/about.html.erb
Pages About

app/views/pages/contact.html.erb
<h1>Pages#Contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/reviews/index.html.erb
testing 1 2 3